#!/bin/sh
# 
# Script for daily install of McStas CVS tarball. To be run using cron.
# May require root priviliges depending on installation path.
#
# Requirements: wget, mktemp and the usual McStas build tools 
#
# PW, Risoe, 20040225

# User configuration
# Where to install:
PREFIX=/home/knoppix/mcstas
# What plotter to use: matlab/scilab/PGPLOT/config (config will autodetect)
PLOTTER=config


# Create temporary folder for the build
TMPDIR=`mktemp /tmp/XXXXXX`
if test -r $TMPDIR
then
  rm -f $TMPDIR
fi
mkdir $TMPDIR

cd $TMPDIR

# Get the archive
wget http://mcstas.risoe.dk/cvs/McStas-Current-src.tar.gz

# Unpack
gunzip -c McStas-Current-src.tar.gz | tar xf -

cd mcstas-*
./configure --prefix=$PREFIX
make 
make $PLOTTER
make install

# Clean up
cd -
rm -rf $TMPDIR
